name: Deploy my-app

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Serverless Devs CLI
      run: npm install -g @serverless-devs/s

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Create .s directory and access config file
      run: |
        mkdir -p .s
        cat <<EOF > .s/access.yaml
        default:
          accountid: ${{ secrets.ALIYUN_ACCOUNT_ID }}
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        EOF
    
    - name: Debug config.yaml  
      run: cat .s/config.yaml  
    
    - name: Create default config file  
      run: |  
        mkdir -p ${HOME}/.s  
        cp .s/config.yaml ${HOME}/.s/access.yaml  
    
    - name: Debug access.yaml  
      run: cat ${HOME}/.s/access.yaml  
    
    - name: Deploy to Aliyun FC  
      if: github.ref == 'refs/heads/develop'  
      env:  
        ALIYUN_ACCOUNT_ID: ${{ secrets.ALIYUN_ACCOUNT_ID }}  
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}  
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}  
        DB_HOST: ${{ secrets.DB_HOST }}  
        DB_PORT: ${{ secrets.DB_PORT }}  
        DB_USERNAME: ${{ secrets.DB_USERNAME }}  
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  
        DB_DATABASE: ${{ secrets.DB_DATABASE }}  
      run: |  
        pwd  
        WORKSPACE=$(pwd)  
        echo "Current workspace: $WORKSPACE"  
        s deploy -y --use-local --skip-push -t ${WORKSPACE}/s.yaml --access default --config ${HOME}/.s/access.yaml --debug  