name: Deploy my-app

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Serverless Devs CLI
      run: npm install -g @serverless-devs/s

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

    - name: Create .s directory and config file  
      run: |  
        mkdir -p ${HOME}/.s  
        cat <<EOF > ${HOME}/.s/access.yaml  
        default:  
          accountid: ${{ secrets.ALIYUN_ACCOUNT_ID }}  
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}  
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}  
        EOF

    - name: Verify access.yaml content (for debugging purposes only)
      run: |
        cat ${HOME}/.s/access.yaml
    
    - name: Check if accountid is present in default section
      run: |
        CONFIG_FILE="${HOME}/.s/access.yaml"
        if [ ! -f "$CONFIG_FILE" ]; then
          echo "Error: Configuration file not found at $CONFIG_FILE"
          exit 1
        fi
        ACCOUNTID=$(yq eval '.default.accountid' "$CONFIG_FILE")
        if [ -z "$ACCOUNTID" ]; then
          echo "Error: 'accountid' field is missing or empty in the 'default' section of $CONFIG_FILE"
          exit 1
        else
          echo "Success: 'accountid' field is present and set to '$ACCOUNTID'"
        fi

    - name: Deploy to Aliyun FC  
      if: github.ref == 'refs/heads/develop'  
      env:  
        ALIYUN_ACCOUNT_ID: ${{ secrets.ALIYUN_ACCOUNT_ID }}  
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}  
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}  
        DB_HOST: ${{ secrets.DB_HOST }}  
        DB_PORT: ${{ secrets.DB_PORT }}  
        DB_USERNAME: ${{ secrets.DB_USERNAME }}  
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  
        DB_DATABASE: ${{ secrets.DB_DATABASE }}  
      run: |  
        cat ${HOME}/.s/access.yaml
        pwd  
        WORKSPACE=$(pwd)  
        echo "Current workspace: $WORKSPACE"  
        s deploy --access-file ${HOME}/.s/access.yaml --debug  